### ISSUE TITLE
TODO - 1st demo

### ISSUE THREAD

**Issue by blomquiste** [Syncopated90/globarch#1]
Code structure
- [ ] Create suitable file structure
- [ ] Start a README (file structure, server instructions, config, osv osv)
- [ ] Comment all code

Database stuff
- [ ] Create database
- [ ] Migrate data of users (to manage login) 

Frameworks
- [ ] Install Node and Express
- [ ] Install React

Functionality flow
- [ ] LoginView
